# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Description', max_length=200)),
                ('address', models.CharField(default='Address', max_length=30)),
                ('status', models.CharField(default='Status', max_length=30)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='As ... I want ...', max_length=128)),
                ('header', models.CharField(default='header', max_length=20)),
                ('top', models.CharField(default='200px', max_length=6)),
                ('left', models.CharField(default='50px', max_length=6)),
                ('width', models.CharField(default='200px', max_length=6)),
                ('heigth', models.CharField(default='100px', max_length=6)),
                ('theme', models.CharField(default='sticky-note-green-theme', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
