# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='point',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.CharField(default='High', max_length=12),
        ),
    ]
