# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20180309_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iteration', models.CharField(default='0', max_length=3)),
                ('status', models.CharField(default='Planned', max_length=15)),
                ('startDate', models.CharField(default='1/1/2018', max_length=20)),
                ('endDate', models.CharField(default='1/1/2018', max_length=20)),
                ('releaseDate', models.CharField(default='1/1/2018', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Project')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Story')),
            ],
        ),
    ]
