# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='status',
        ),
    ]
